# Generated by Django 4.2.6 on 2023-10-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='team',
            new_name='teams',
        ),
    ]
